# Generated by Django 5.0.7 on 2024-07-30 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0002_chatgptrequest_chatgptresponse'),
    ]

    operations = [
        migrations.CreateModel(
            name='CampaignPrompt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
